# Generated by Django 4.1.7 on 2023-04-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
